// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum ClientHostApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum HostPlatform: Int, CaseIterable {
  case unknown = 0
  case windows = 1
  case ios = 2
}

enum ProfileOrigin: Int, CaseIterable {
  case unknown = 0
  case imported = 1
  case cluster = 2
}

enum TunnelState: Int, CaseIterable {
  case unknown = 0
  case disconnected = 1
  case connecting = 2
  case connected = 3
  case reconnecting = 4
  case disconnecting = 5
  case failed = 6
}

enum CarrierKind: Int, CaseIterable {
  case unknown = 0
  case none = 1
  case http3WebTransport = 2
}

enum HostErrorCode: Int, CaseIterable {
  case unknown = 0
  case hostUnavailable = 1
  case unsupportedApiVersion = 2
  case invalidProfile = 3
  case credentialUnavailable = 4
  case noSafeUplink = 5
  case dnsFailed = 6
  case udpUnreachable = 7
  case tlsFailed = 8
  case http3Timeout = 9
  case np2AuthFailed = 10
  case tunSetupFailed = 11
  case cancelled = 12
  case internalFailure = 13
}

enum ErrorStage: Int, CaseIterable {
  case unknown = 0
  case hostIpc = 1
  case hostNegotiation = 2
  case profileValidation = 3
  case credentialLoad = 4
  case dnsResolution = 5
  case endpointRoute = 6
  case quicHandshake = 7
  case tlsHandshake = 8
  case webTransportConnect = 9
  case np2Authentication = 10
  case tunSetup = 11
  case packetForwarding = 12
}

enum DiagnosticLevel: Int, CaseIterable {
  case unknown = 0
  case info = 1
  case warning = 2
  case error = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostApiVersion: Hashable, CustomStringConvertible {
  var major: Int64
  var minor: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostApiVersion? {
    let major = pigeonVar_list[0] as! Int64
    let minor = pigeonVar_list[1] as! Int64

    return HostApiVersion(
      major: major,
      minor: minor
    )
  }
  func toList() -> [Any?] {
    return [
      major,
      minor,
    ]
  }
  static func == (lhs: HostApiVersion, rhs: HostApiVersion) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.major, rhs.major) && ClientHostApiPigeonInternal.deepEquals(lhs.minor, rhs.minor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostApiVersion")
    ClientHostApiPigeonInternal.deepHash(value: major, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: minor, hasher: &hasher)
  }

  public var description: String {
    return "HostApiVersion(major: \(String(describing: major)), minor: \(String(describing: minor)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostCapabilities: Hashable, CustomStringConvertible {
  var apiVersion: HostApiVersion
  var platform: HostPlatform
  var appVersion: String
  var hostVersion: String
  var coreVersion: String
  var supportsHttp3WebTransport: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostCapabilities? {
    let apiVersion = pigeonVar_list[0] as! HostApiVersion
    let platform = pigeonVar_list[1] as! HostPlatform
    let appVersion = pigeonVar_list[2] as! String
    let hostVersion = pigeonVar_list[3] as! String
    let coreVersion = pigeonVar_list[4] as! String
    let supportsHttp3WebTransport = pigeonVar_list[5] as! Bool

    return HostCapabilities(
      apiVersion: apiVersion,
      platform: platform,
      appVersion: appVersion,
      hostVersion: hostVersion,
      coreVersion: coreVersion,
      supportsHttp3WebTransport: supportsHttp3WebTransport
    )
  }
  func toList() -> [Any?] {
    return [
      apiVersion,
      platform,
      appVersion,
      hostVersion,
      coreVersion,
      supportsHttp3WebTransport,
    ]
  }
  static func == (lhs: HostCapabilities, rhs: HostCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.apiVersion, rhs.apiVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.platform, rhs.platform) && ClientHostApiPigeonInternal.deepEquals(lhs.appVersion, rhs.appVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.hostVersion, rhs.hostVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.coreVersion, rhs.coreVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.supportsHttp3WebTransport, rhs.supportsHttp3WebTransport)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostCapabilities")
    ClientHostApiPigeonInternal.deepHash(value: apiVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: appVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: hostVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: coreVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: supportsHttp3WebTransport, hasher: &hasher)
  }

  public var description: String {
    return "HostCapabilities(apiVersion: \(String(describing: apiVersion)), platform: \(String(describing: platform)), appVersion: \(String(describing: appVersion)), hostVersion: \(String(describing: hostVersion)), coreVersion: \(String(describing: coreVersion)), supportsHttp3WebTransport: \(String(describing: supportsHttp3WebTransport)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProfileSummary: Hashable, CustomStringConvertible {
  var id: String
  var displayName: String
  var serverIdentity: String
  var host: String
  var selected: Bool
  var hasCredential: Bool
  var origin: ProfileOrigin
  var catalogManaged: Bool
  var updatedAtUnixMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProfileSummary? {
    let id = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String
    let serverIdentity = pigeonVar_list[2] as! String
    let host = pigeonVar_list[3] as! String
    let selected = pigeonVar_list[4] as! Bool
    let hasCredential = pigeonVar_list[5] as! Bool
    let origin = pigeonVar_list[6] as! ProfileOrigin
    let catalogManaged = pigeonVar_list[7] as! Bool
    let updatedAtUnixMs = pigeonVar_list[8] as! Int64

    return ProfileSummary(
      id: id,
      displayName: displayName,
      serverIdentity: serverIdentity,
      host: host,
      selected: selected,
      hasCredential: hasCredential,
      origin: origin,
      catalogManaged: catalogManaged,
      updatedAtUnixMs: updatedAtUnixMs
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      displayName,
      serverIdentity,
      host,
      selected,
      hasCredential,
      origin,
      catalogManaged,
      updatedAtUnixMs,
    ]
  }
  static func == (lhs: ProfileSummary, rhs: ProfileSummary) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.id, rhs.id) && ClientHostApiPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && ClientHostApiPigeonInternal.deepEquals(lhs.serverIdentity, rhs.serverIdentity) && ClientHostApiPigeonInternal.deepEquals(lhs.host, rhs.host) && ClientHostApiPigeonInternal.deepEquals(lhs.selected, rhs.selected) && ClientHostApiPigeonInternal.deepEquals(lhs.hasCredential, rhs.hasCredential) && ClientHostApiPigeonInternal.deepEquals(lhs.origin, rhs.origin) && ClientHostApiPigeonInternal.deepEquals(lhs.catalogManaged, rhs.catalogManaged) && ClientHostApiPigeonInternal.deepEquals(lhs.updatedAtUnixMs, rhs.updatedAtUnixMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProfileSummary")
    ClientHostApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: serverIdentity, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: host, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: selected, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: hasCredential, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: origin, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: catalogManaged, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: updatedAtUnixMs, hasher: &hasher)
  }

  public var description: String {
    return "ProfileSummary(id: \(String(describing: id)), displayName: \(String(describing: displayName)), serverIdentity: \(String(describing: serverIdentity)), host: \(String(describing: host)), selected: \(String(describing: selected)), hasCredential: \(String(describing: hasCredential)), origin: \(String(describing: origin)), catalogManaged: \(String(describing: catalogManaged)), updatedAtUnixMs: \(String(describing: updatedAtUnixMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImportProfileRequest: Hashable, CustomStringConvertible {
  var onboardingValue: String
  var operationId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImportProfileRequest? {
    let onboardingValue = pigeonVar_list[0] as! String
    let operationId = pigeonVar_list[1] as! String

    return ImportProfileRequest(
      onboardingValue: onboardingValue,
      operationId: operationId
    )
  }
  func toList() -> [Any?] {
    return [
      onboardingValue,
      operationId,
    ]
  }
  static func == (lhs: ImportProfileRequest, rhs: ImportProfileRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.onboardingValue, rhs.onboardingValue) && ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImportProfileRequest")
    ClientHostApiPigeonInternal.deepHash(value: onboardingValue, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
  }

  public var description: String {
    return "ImportProfileRequest(onboardingValue: \(String(describing: onboardingValue)), operationId: \(String(describing: operationId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SelectProfileRequest: Hashable, CustomStringConvertible {
  var profileId: String
  var operationId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SelectProfileRequest? {
    let profileId = pigeonVar_list[0] as! String
    let operationId = pigeonVar_list[1] as! String

    return SelectProfileRequest(
      profileId: profileId,
      operationId: operationId
    )
  }
  func toList() -> [Any?] {
    return [
      profileId,
      operationId,
    ]
  }
  static func == (lhs: SelectProfileRequest, rhs: SelectProfileRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.profileId, rhs.profileId) && ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SelectProfileRequest")
    ClientHostApiPigeonInternal.deepHash(value: profileId, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
  }

  public var description: String {
    return "SelectProfileRequest(profileId: \(String(describing: profileId)), operationId: \(String(describing: operationId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RemoveProfileRequest: Hashable, CustomStringConvertible {
  var profileId: String
  var force: Bool
  var operationId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RemoveProfileRequest? {
    let profileId = pigeonVar_list[0] as! String
    let force = pigeonVar_list[1] as! Bool
    let operationId = pigeonVar_list[2] as! String

    return RemoveProfileRequest(
      profileId: profileId,
      force: force,
      operationId: operationId
    )
  }
  func toList() -> [Any?] {
    return [
      profileId,
      force,
      operationId,
    ]
  }
  static func == (lhs: RemoveProfileRequest, rhs: RemoveProfileRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.profileId, rhs.profileId) && ClientHostApiPigeonInternal.deepEquals(lhs.force, rhs.force) && ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RemoveProfileRequest")
    ClientHostApiPigeonInternal.deepHash(value: profileId, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: force, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
  }

  public var description: String {
    return "RemoveProfileRequest(profileId: \(String(describing: profileId)), force: \(String(describing: force)), operationId: \(String(describing: operationId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectRequest: Hashable, CustomStringConvertible {
  var profileId: String
  var operationId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectRequest? {
    let profileId = pigeonVar_list[0] as! String
    let operationId = pigeonVar_list[1] as! String

    return ConnectRequest(
      profileId: profileId,
      operationId: operationId
    )
  }
  func toList() -> [Any?] {
    return [
      profileId,
      operationId,
    ]
  }
  static func == (lhs: ConnectRequest, rhs: ConnectRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.profileId, rhs.profileId) && ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectRequest")
    ClientHostApiPigeonInternal.deepHash(value: profileId, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
  }

  public var description: String {
    return "ConnectRequest(profileId: \(String(describing: profileId)), operationId: \(String(describing: operationId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DisconnectRequest: Hashable, CustomStringConvertible {
  var operationId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisconnectRequest? {
    let operationId = pigeonVar_list[0] as! String

    return DisconnectRequest(
      operationId: operationId
    )
  }
  func toList() -> [Any?] {
    return [
      operationId
    ]
  }
  static func == (lhs: DisconnectRequest, rhs: DisconnectRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DisconnectRequest")
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
  }

  public var description: String {
    return "DisconnectRequest(operationId: \(String(describing: operationId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostError: Hashable, CustomStringConvertible {
  var code: HostErrorCode
  var stage: ErrorStage
  var message: String
  var retryable: Bool
  var operationId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostError? {
    let code = pigeonVar_list[0] as! HostErrorCode
    let stage = pigeonVar_list[1] as! ErrorStage
    let message = pigeonVar_list[2] as! String
    let retryable = pigeonVar_list[3] as! Bool
    let operationId = pigeonVar_list[4] as! String

    return HostError(
      code: code,
      stage: stage,
      message: message,
      retryable: retryable,
      operationId: operationId
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      stage,
      message,
      retryable,
      operationId,
    ]
  }
  static func == (lhs: HostError, rhs: HostError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.code, rhs.code) && ClientHostApiPigeonInternal.deepEquals(lhs.stage, rhs.stage) && ClientHostApiPigeonInternal.deepEquals(lhs.message, rhs.message) && ClientHostApiPigeonInternal.deepEquals(lhs.retryable, rhs.retryable) && ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostError")
    ClientHostApiPigeonInternal.deepHash(value: code, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: stage, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: retryable, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
  }

  public var description: String {
    return "HostError(code: \(String(describing: code)), stage: \(String(describing: stage)), message: \(String(describing: message)), retryable: \(String(describing: retryable)), operationId: \(String(describing: operationId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TunnelStatus: Hashable, CustomStringConvertible {
  var state: TunnelState
  var profileId: String? = nil
  var carrier: CarrierKind
  var connectedAtUnixMs: Int64
  var uploadBytesPerSecond: Int64
  var downloadBytesPerSecond: Int64
  var uploadTotalBytes: Int64
  var downloadTotalBytes: Int64
  var sequence: Int64
  var lastError: HostError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TunnelStatus? {
    let state = pigeonVar_list[0] as! TunnelState
    let profileId: String? = nilOrValue(pigeonVar_list[1])
    let carrier = pigeonVar_list[2] as! CarrierKind
    let connectedAtUnixMs = pigeonVar_list[3] as! Int64
    let uploadBytesPerSecond = pigeonVar_list[4] as! Int64
    let downloadBytesPerSecond = pigeonVar_list[5] as! Int64
    let uploadTotalBytes = pigeonVar_list[6] as! Int64
    let downloadTotalBytes = pigeonVar_list[7] as! Int64
    let sequence = pigeonVar_list[8] as! Int64
    let lastError: HostError? = nilOrValue(pigeonVar_list[9])

    return TunnelStatus(
      state: state,
      profileId: profileId,
      carrier: carrier,
      connectedAtUnixMs: connectedAtUnixMs,
      uploadBytesPerSecond: uploadBytesPerSecond,
      downloadBytesPerSecond: downloadBytesPerSecond,
      uploadTotalBytes: uploadTotalBytes,
      downloadTotalBytes: downloadTotalBytes,
      sequence: sequence,
      lastError: lastError
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      profileId,
      carrier,
      connectedAtUnixMs,
      uploadBytesPerSecond,
      downloadBytesPerSecond,
      uploadTotalBytes,
      downloadTotalBytes,
      sequence,
      lastError,
    ]
  }
  static func == (lhs: TunnelStatus, rhs: TunnelStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.state, rhs.state) && ClientHostApiPigeonInternal.deepEquals(lhs.profileId, rhs.profileId) && ClientHostApiPigeonInternal.deepEquals(lhs.carrier, rhs.carrier) && ClientHostApiPigeonInternal.deepEquals(lhs.connectedAtUnixMs, rhs.connectedAtUnixMs) && ClientHostApiPigeonInternal.deepEquals(lhs.uploadBytesPerSecond, rhs.uploadBytesPerSecond) && ClientHostApiPigeonInternal.deepEquals(lhs.downloadBytesPerSecond, rhs.downloadBytesPerSecond) && ClientHostApiPigeonInternal.deepEquals(lhs.uploadTotalBytes, rhs.uploadTotalBytes) && ClientHostApiPigeonInternal.deepEquals(lhs.downloadTotalBytes, rhs.downloadTotalBytes) && ClientHostApiPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && ClientHostApiPigeonInternal.deepEquals(lhs.lastError, rhs.lastError)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TunnelStatus")
    ClientHostApiPigeonInternal.deepHash(value: state, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: profileId, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: carrier, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: connectedAtUnixMs, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: uploadBytesPerSecond, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: downloadBytesPerSecond, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: uploadTotalBytes, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: downloadTotalBytes, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: lastError, hasher: &hasher)
  }

  public var description: String {
    return "TunnelStatus(state: \(String(describing: state)), profileId: \(String(describing: profileId)), carrier: \(String(describing: carrier)), connectedAtUnixMs: \(String(describing: connectedAtUnixMs)), uploadBytesPerSecond: \(String(describing: uploadBytesPerSecond)), downloadBytesPerSecond: \(String(describing: downloadBytesPerSecond)), uploadTotalBytes: \(String(describing: uploadTotalBytes)), downloadTotalBytes: \(String(describing: downloadTotalBytes)), sequence: \(String(describing: sequence)), lastError: \(String(describing: lastError)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiagnosticsRequest: Hashable, CustomStringConvertible {
  var limit: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiagnosticsRequest? {
    let limit = pigeonVar_list[0] as! Int64

    return DiagnosticsRequest(
      limit: limit
    )
  }
  func toList() -> [Any?] {
    return [
      limit
    ]
  }
  static func == (lhs: DiagnosticsRequest, rhs: DiagnosticsRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.limit, rhs.limit)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DiagnosticsRequest")
    ClientHostApiPigeonInternal.deepHash(value: limit, hasher: &hasher)
  }

  public var description: String {
    return "DiagnosticsRequest(limit: \(String(describing: limit)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiagnosticEvent: Hashable, CustomStringConvertible {
  var unixMs: Int64
  var level: DiagnosticLevel
  var stage: ErrorStage
  var code: HostErrorCode? = nil
  var message: String
  var operationId: String
  var sequence: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiagnosticEvent? {
    let unixMs = pigeonVar_list[0] as! Int64
    let level = pigeonVar_list[1] as! DiagnosticLevel
    let stage = pigeonVar_list[2] as! ErrorStage
    let code: HostErrorCode? = nilOrValue(pigeonVar_list[3])
    let message = pigeonVar_list[4] as! String
    let operationId = pigeonVar_list[5] as! String
    let sequence = pigeonVar_list[6] as! Int64

    return DiagnosticEvent(
      unixMs: unixMs,
      level: level,
      stage: stage,
      code: code,
      message: message,
      operationId: operationId,
      sequence: sequence
    )
  }
  func toList() -> [Any?] {
    return [
      unixMs,
      level,
      stage,
      code,
      message,
      operationId,
      sequence,
    ]
  }
  static func == (lhs: DiagnosticEvent, rhs: DiagnosticEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.unixMs, rhs.unixMs) && ClientHostApiPigeonInternal.deepEquals(lhs.level, rhs.level) && ClientHostApiPigeonInternal.deepEquals(lhs.stage, rhs.stage) && ClientHostApiPigeonInternal.deepEquals(lhs.code, rhs.code) && ClientHostApiPigeonInternal.deepEquals(lhs.message, rhs.message) && ClientHostApiPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && ClientHostApiPigeonInternal.deepEquals(lhs.sequence, rhs.sequence)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DiagnosticEvent")
    ClientHostApiPigeonInternal.deepHash(value: unixMs, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: level, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: stage, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: code, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: sequence, hasher: &hasher)
  }

  public var description: String {
    return "DiagnosticEvent(unixMs: \(String(describing: unixMs)), level: \(String(describing: level)), stage: \(String(describing: stage)), code: \(String(describing: code)), message: \(String(describing: message)), operationId: \(String(describing: operationId)), sequence: \(String(describing: sequence)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiagnosticsSnapshot: Hashable, CustomStringConvertible {
  var appVersion: String
  var hostVersion: String
  var coreVersion: String
  var carrierPolicy: String
  var currentCarrier: CarrierKind
  var reconnectCount: Int64
  var events: [DiagnosticEvent]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiagnosticsSnapshot? {
    let appVersion = pigeonVar_list[0] as! String
    let hostVersion = pigeonVar_list[1] as! String
    let coreVersion = pigeonVar_list[2] as! String
    let carrierPolicy = pigeonVar_list[3] as! String
    let currentCarrier = pigeonVar_list[4] as! CarrierKind
    let reconnectCount = pigeonVar_list[5] as! Int64
    let events = pigeonVar_list[6] as! [DiagnosticEvent]

    return DiagnosticsSnapshot(
      appVersion: appVersion,
      hostVersion: hostVersion,
      coreVersion: coreVersion,
      carrierPolicy: carrierPolicy,
      currentCarrier: currentCarrier,
      reconnectCount: reconnectCount,
      events: events
    )
  }
  func toList() -> [Any?] {
    return [
      appVersion,
      hostVersion,
      coreVersion,
      carrierPolicy,
      currentCarrier,
      reconnectCount,
      events,
    ]
  }
  static func == (lhs: DiagnosticsSnapshot, rhs: DiagnosticsSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.appVersion, rhs.appVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.hostVersion, rhs.hostVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.coreVersion, rhs.coreVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.carrierPolicy, rhs.carrierPolicy) && ClientHostApiPigeonInternal.deepEquals(lhs.currentCarrier, rhs.currentCarrier) && ClientHostApiPigeonInternal.deepEquals(lhs.reconnectCount, rhs.reconnectCount) && ClientHostApiPigeonInternal.deepEquals(lhs.events, rhs.events)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DiagnosticsSnapshot")
    ClientHostApiPigeonInternal.deepHash(value: appVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: hostVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: coreVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: carrierPolicy, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: currentCarrier, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: reconnectCount, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: events, hasher: &hasher)
  }

  public var description: String {
    return "DiagnosticsSnapshot(appVersion: \(String(describing: appVersion)), hostVersion: \(String(describing: hostVersion)), coreVersion: \(String(describing: coreVersion)), carrierPolicy: \(String(describing: carrierPolicy)), currentCarrier: \(String(describing: currentCarrier)), reconnectCount: \(String(describing: reconnectCount)), events: \(String(describing: events)))"
  }
}

private class ClientHostApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HostPlatform(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ProfileOrigin(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TunnelState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CarrierKind(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HostErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ErrorStage(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DiagnosticLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return HostApiVersion.fromList(self.readValue() as! [Any?])
    case 137:
      return HostCapabilities.fromList(self.readValue() as! [Any?])
    case 138:
      return ProfileSummary.fromList(self.readValue() as! [Any?])
    case 139:
      return ImportProfileRequest.fromList(self.readValue() as! [Any?])
    case 140:
      return SelectProfileRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return RemoveProfileRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return ConnectRequest.fromList(self.readValue() as! [Any?])
    case 143:
      return DisconnectRequest.fromList(self.readValue() as! [Any?])
    case 144:
      return HostError.fromList(self.readValue() as! [Any?])
    case 145:
      return TunnelStatus.fromList(self.readValue() as! [Any?])
    case 146:
      return DiagnosticsRequest.fromList(self.readValue() as! [Any?])
    case 147:
      return DiagnosticEvent.fromList(self.readValue() as! [Any?])
    case 148:
      return DiagnosticsSnapshot.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ClientHostApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HostPlatform {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ProfileOrigin {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? TunnelState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? CarrierKind {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? HostErrorCode {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? ErrorStage {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? DiagnosticLevel {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? HostApiVersion {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? HostCapabilities {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ProfileSummary {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ImportProfileRequest {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? SelectProfileRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? RemoveProfileRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? DisconnectRequest {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? HostError {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? TunnelStatus {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? DiagnosticsRequest {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? DiagnosticEvent {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? DiagnosticsSnapshot {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ClientHostApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ClientHostApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ClientHostApiPigeonCodecWriter(data: data)
  }
}

class ClientHostApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ClientHostApiPigeonCodec(readerWriter: ClientHostApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ClientHostApi {
  func getCapabilities(requestedVersion: HostApiVersion) async throws -> HostCapabilities
  func listProfiles() async throws -> [ProfileSummary]
  func importProfile(request: ImportProfileRequest) async throws -> ProfileSummary
  func selectProfile(request: SelectProfileRequest) async throws -> ProfileSummary
  func removeProfile(request: RemoveProfileRequest) async throws
  func connect(request: ConnectRequest) async throws -> TunnelStatus
  func disconnect(request: DisconnectRequest) async throws -> TunnelStatus
  func getStatus() async throws -> TunnelStatus
  func getDiagnostics(request: DiagnosticsRequest) async throws -> DiagnosticsSnapshot
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ClientHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ClientHostApiPigeonCodec.shared }
  /// Sets up an instance of `ClientHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ClientHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestedVersionArg = args[0] as! HostApiVersion
        Task { @MainActor in
          do {
            let result = try await api.getCapabilities(requestedVersion: requestedVersionArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let listProfilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.listProfiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listProfilesChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.listProfiles()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      listProfilesChannel.setMessageHandler(nil)
    }
    let importProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.importProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ImportProfileRequest
        Task { @MainActor in
          do {
            let result = try await api.importProfile(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      importProfileChannel.setMessageHandler(nil)
    }
    let selectProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.selectProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SelectProfileRequest
        Task { @MainActor in
          do {
            let result = try await api.selectProfile(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      selectProfileChannel.setMessageHandler(nil)
    }
    let removeProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.removeProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RemoveProfileRequest
        Task { @MainActor in
          do {
            try await api.removeProfile(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeProfileChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ConnectRequest
        Task { @MainActor in
          do {
            let result = try await api.connect(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DisconnectRequest
        Task { @MainActor in
          do {
            let result = try await api.disconnect(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let getStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.getStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getStatus()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStatusChannel.setMessageHandler(nil)
    }
    let getDiagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.getDiagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDiagnosticsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DiagnosticsRequest
        Task { @MainActor in
          do {
            let result = try await api.getDiagnostics(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDiagnosticsChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ClientHostFlutterApiProtocol {
  func statusChanged(status statusArg: TunnelStatus) async throws
}
class ClientHostFlutterApi: ClientHostFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ClientHostApiPigeonCodec {
    return ClientHostApiPigeonCodec.shared
  }
  func statusChanged(status statusArg: TunnelStatus) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.neproto_host.ClientHostFlutterApi.statusChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([statusArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
