// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum ClientHostApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum HostPlatform: Int, CaseIterable {
  case unknown = 0
  case windows = 1
  case ios = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostApiVersion: Hashable, CustomStringConvertible {
  var major: Int64
  var minor: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostApiVersion? {
    let major = pigeonVar_list[0] as! Int64
    let minor = pigeonVar_list[1] as! Int64

    return HostApiVersion(
      major: major,
      minor: minor
    )
  }
  func toList() -> [Any?] {
    return [
      major,
      minor,
    ]
  }
  static func == (lhs: HostApiVersion, rhs: HostApiVersion) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.major, rhs.major) && ClientHostApiPigeonInternal.deepEquals(lhs.minor, rhs.minor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostApiVersion")
    ClientHostApiPigeonInternal.deepHash(value: major, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: minor, hasher: &hasher)
  }

  public var description: String {
    return "HostApiVersion(major: \(String(describing: major)), minor: \(String(describing: minor)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostCapabilities: Hashable, CustomStringConvertible {
  var apiVersion: HostApiVersion
  var platform: HostPlatform
  var appVersion: String
  var hostVersion: String
  var coreVersion: String
  var supportsHttp3WebTransport: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostCapabilities? {
    let apiVersion = pigeonVar_list[0] as! HostApiVersion
    let platform = pigeonVar_list[1] as! HostPlatform
    let appVersion = pigeonVar_list[2] as! String
    let hostVersion = pigeonVar_list[3] as! String
    let coreVersion = pigeonVar_list[4] as! String
    let supportsHttp3WebTransport = pigeonVar_list[5] as! Bool

    return HostCapabilities(
      apiVersion: apiVersion,
      platform: platform,
      appVersion: appVersion,
      hostVersion: hostVersion,
      coreVersion: coreVersion,
      supportsHttp3WebTransport: supportsHttp3WebTransport
    )
  }
  func toList() -> [Any?] {
    return [
      apiVersion,
      platform,
      appVersion,
      hostVersion,
      coreVersion,
      supportsHttp3WebTransport,
    ]
  }
  static func == (lhs: HostCapabilities, rhs: HostCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClientHostApiPigeonInternal.deepEquals(lhs.apiVersion, rhs.apiVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.platform, rhs.platform) && ClientHostApiPigeonInternal.deepEquals(lhs.appVersion, rhs.appVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.hostVersion, rhs.hostVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.coreVersion, rhs.coreVersion) && ClientHostApiPigeonInternal.deepEquals(lhs.supportsHttp3WebTransport, rhs.supportsHttp3WebTransport)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostCapabilities")
    ClientHostApiPigeonInternal.deepHash(value: apiVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: appVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: hostVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: coreVersion, hasher: &hasher)
    ClientHostApiPigeonInternal.deepHash(value: supportsHttp3WebTransport, hasher: &hasher)
  }

  public var description: String {
    return "HostCapabilities(apiVersion: \(String(describing: apiVersion)), platform: \(String(describing: platform)), appVersion: \(String(describing: appVersion)), hostVersion: \(String(describing: hostVersion)), coreVersion: \(String(describing: coreVersion)), supportsHttp3WebTransport: \(String(describing: supportsHttp3WebTransport)))"
  }
}

private class ClientHostApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HostPlatform(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return HostApiVersion.fromList(self.readValue() as! [Any?])
    case 131:
      return HostCapabilities.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ClientHostApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HostPlatform {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HostApiVersion {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? HostCapabilities {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ClientHostApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ClientHostApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ClientHostApiPigeonCodecWriter(data: data)
  }
}

class ClientHostApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ClientHostApiPigeonCodec(readerWriter: ClientHostApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ClientHostApi {
  func getCapabilities(requestedVersion: HostApiVersion) async throws -> HostCapabilities
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ClientHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ClientHostApiPigeonCodec.shared }
  /// Sets up an instance of `ClientHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ClientHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neproto_host.ClientHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestedVersionArg = args[0] as! HostApiVersion
        Task { @MainActor in
          do {
            let result = try await api.getCapabilities(requestedVersion: requestedVersionArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
  }
}
