name: neproto_client
description: Shared Windows and iOS application layer for NeProto.
publish_to: 'none'
version: 0.5.18+18

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  neproto_host:
    path: ../plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
