// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "client_host_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace neproto_host {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// HostApiVersion

HostApiVersion::HostApiVersion(
  int64_t major,
  int64_t minor)
 : major_(major),
    minor_(minor) {}

int64_t HostApiVersion::major() const {
  return major_;
}

void HostApiVersion::set_major(int64_t value_arg) {
  major_ = value_arg;
}


int64_t HostApiVersion::minor() const {
  return minor_;
}

void HostApiVersion::set_minor(int64_t value_arg) {
  minor_ = value_arg;
}


EncodableList HostApiVersion::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(major_));
  list.push_back(EncodableValue(minor_));
  return list;
}

HostApiVersion HostApiVersion::FromEncodableList(const EncodableList& list) {
  HostApiVersion decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]));
  return decoded;
}

bool HostApiVersion::operator==(const HostApiVersion& other) const {
  return PigeonInternalDeepEquals(major_, other.major_) && PigeonInternalDeepEquals(minor_, other.minor_);
}

bool HostApiVersion::operator!=(const HostApiVersion& other) const {
  return !(*this == other);
}

size_t HostApiVersion::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(major_);
  result = result * 31 + PigeonInternalDeepHash(minor_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const HostApiVersion& obj) {
  os << "HostApiVersion(";
  os << "major: ";
  os << PigeonInternalToString(obj.major_);
  os << ", minor: ";
  os << PigeonInternalToString(obj.minor_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const HostApiVersion& v) {
  return v.Hash();
}

// HostCapabilities

HostCapabilities::HostCapabilities(
  const HostApiVersion& api_version,
  const HostPlatform& platform,
  const std::string& app_version,
  const std::string& host_version,
  const std::string& core_version,
  bool supports_http3_web_transport)
 : api_version_(std::make_unique<HostApiVersion>(api_version)),
    platform_(platform),
    app_version_(app_version),
    host_version_(host_version),
    core_version_(core_version),
    supports_http3_web_transport_(supports_http3_web_transport) {}

HostCapabilities::HostCapabilities(const HostCapabilities& other)
 : api_version_(std::make_unique<HostApiVersion>(*other.api_version_)),
    platform_(other.platform_),
    app_version_(other.app_version_),
    host_version_(other.host_version_),
    core_version_(other.core_version_),
    supports_http3_web_transport_(other.supports_http3_web_transport_) {}

HostCapabilities& HostCapabilities::operator=(const HostCapabilities& other) {
  api_version_ = std::make_unique<HostApiVersion>(*other.api_version_);
  platform_ = other.platform_;
  app_version_ = other.app_version_;
  host_version_ = other.host_version_;
  core_version_ = other.core_version_;
  supports_http3_web_transport_ = other.supports_http3_web_transport_;
  return *this;
}

const HostApiVersion& HostCapabilities::api_version() const {
  return *api_version_;
}

void HostCapabilities::set_api_version(const HostApiVersion& value_arg) {
  api_version_ = std::make_unique<HostApiVersion>(value_arg);
}


const HostPlatform& HostCapabilities::platform() const {
  return platform_;
}

void HostCapabilities::set_platform(const HostPlatform& value_arg) {
  platform_ = value_arg;
}


const std::string& HostCapabilities::app_version() const {
  return app_version_;
}

void HostCapabilities::set_app_version(std::string_view value_arg) {
  app_version_ = value_arg;
}


const std::string& HostCapabilities::host_version() const {
  return host_version_;
}

void HostCapabilities::set_host_version(std::string_view value_arg) {
  host_version_ = value_arg;
}


const std::string& HostCapabilities::core_version() const {
  return core_version_;
}

void HostCapabilities::set_core_version(std::string_view value_arg) {
  core_version_ = value_arg;
}


bool HostCapabilities::supports_http3_web_transport() const {
  return supports_http3_web_transport_;
}

void HostCapabilities::set_supports_http3_web_transport(bool value_arg) {
  supports_http3_web_transport_ = value_arg;
}


EncodableList HostCapabilities::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(CustomEncodableValue(*api_version_));
  list.push_back(CustomEncodableValue(platform_));
  list.push_back(EncodableValue(app_version_));
  list.push_back(EncodableValue(host_version_));
  list.push_back(EncodableValue(core_version_));
  list.push_back(EncodableValue(supports_http3_web_transport_));
  return list;
}

HostCapabilities HostCapabilities::FromEncodableList(const EncodableList& list) {
  HostCapabilities decoded(
    std::any_cast<const HostApiVersion&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const HostPlatform&>(std::get<CustomEncodableValue>(list[1])),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::get<bool>(list[5]));
  return decoded;
}

bool HostCapabilities::operator==(const HostCapabilities& other) const {
  return PigeonInternalDeepEquals(api_version_, other.api_version_) && PigeonInternalDeepEquals(platform_, other.platform_) && PigeonInternalDeepEquals(app_version_, other.app_version_) && PigeonInternalDeepEquals(host_version_, other.host_version_) && PigeonInternalDeepEquals(core_version_, other.core_version_) && PigeonInternalDeepEquals(supports_http3_web_transport_, other.supports_http3_web_transport_);
}

bool HostCapabilities::operator!=(const HostCapabilities& other) const {
  return !(*this == other);
}

size_t HostCapabilities::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(api_version_);
  result = result * 31 + PigeonInternalDeepHash(platform_);
  result = result * 31 + PigeonInternalDeepHash(app_version_);
  result = result * 31 + PigeonInternalDeepHash(host_version_);
  result = result * 31 + PigeonInternalDeepHash(core_version_);
  result = result * 31 + PigeonInternalDeepHash(supports_http3_web_transport_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const HostCapabilities& obj) {
  os << "HostCapabilities(";
  os << "api_version: ";
  os << obj.api_version_;
  os << ", platform: ";
  os << PigeonInternalToString(obj.platform_);
  os << ", app_version: ";
  os << PigeonInternalToString(obj.app_version_);
  os << ", host_version: ";
  os << PigeonInternalToString(obj.host_version_);
  os << ", core_version: ";
  os << PigeonInternalToString(obj.core_version_);
  os << ", supports_http3_web_transport: ";
  os << PigeonInternalToString(obj.supports_http3_web_transport_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const HostCapabilities& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<HostPlatform>(enum_arg_value));
      }
    case 130: {
        return CustomEncodableValue(HostApiVersion::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(HostCapabilities::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(HostPlatform)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<HostPlatform>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(HostApiVersion)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<HostApiVersion>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(HostCapabilities)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<HostCapabilities>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by ClientHostApi.
const ::flutter::StandardMessageCodec& ClientHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `ClientHostApi` to handle messages through the `binary_messenger`.
void ClientHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  ClientHostApi* api) {
  ClientHostApi::SetUp(binary_messenger, api, "");
}

void ClientHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  ClientHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.getCapabilities" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_requested_version_arg = args.at(0);
          if (encodable_requested_version_arg.IsNull()) {
            reply(WrapError("requested_version_arg unexpectedly null."));
            return;
          }
          const auto& requested_version_arg = std::any_cast<const HostApiVersion&>(std::get<CustomEncodableValue>(encodable_requested_version_arg));
          api->GetCapabilities(requested_version_arg, [reply](ErrorOr<HostCapabilities>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue ClientHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue ClientHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace neproto_host
