// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "client_host_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace neproto_host {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// HostApiVersion

HostApiVersion::HostApiVersion(
  int64_t major,
  int64_t minor)
 : major_(major),
    minor_(minor) {}

int64_t HostApiVersion::major() const {
  return major_;
}

void HostApiVersion::set_major(int64_t value_arg) {
  major_ = value_arg;
}


int64_t HostApiVersion::minor() const {
  return minor_;
}

void HostApiVersion::set_minor(int64_t value_arg) {
  minor_ = value_arg;
}


EncodableList HostApiVersion::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(major_));
  list.push_back(EncodableValue(minor_));
  return list;
}

HostApiVersion HostApiVersion::FromEncodableList(const EncodableList& list) {
  HostApiVersion decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]));
  return decoded;
}

bool HostApiVersion::operator==(const HostApiVersion& other) const {
  return PigeonInternalDeepEquals(major_, other.major_) && PigeonInternalDeepEquals(minor_, other.minor_);
}

bool HostApiVersion::operator!=(const HostApiVersion& other) const {
  return !(*this == other);
}

size_t HostApiVersion::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(major_);
  result = result * 31 + PigeonInternalDeepHash(minor_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const HostApiVersion& obj) {
  os << "HostApiVersion(";
  os << "major: ";
  os << PigeonInternalToString(obj.major_);
  os << ", minor: ";
  os << PigeonInternalToString(obj.minor_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const HostApiVersion& v) {
  return v.Hash();
}

// HostCapabilities

HostCapabilities::HostCapabilities(
  const HostApiVersion& api_version,
  const HostPlatform& platform,
  const std::string& app_version,
  const std::string& host_version,
  const std::string& core_version,
  bool supports_http3_web_transport)
 : api_version_(std::make_unique<HostApiVersion>(api_version)),
    platform_(platform),
    app_version_(app_version),
    host_version_(host_version),
    core_version_(core_version),
    supports_http3_web_transport_(supports_http3_web_transport) {}

HostCapabilities::HostCapabilities(const HostCapabilities& other)
 : api_version_(std::make_unique<HostApiVersion>(*other.api_version_)),
    platform_(other.platform_),
    app_version_(other.app_version_),
    host_version_(other.host_version_),
    core_version_(other.core_version_),
    supports_http3_web_transport_(other.supports_http3_web_transport_) {}

HostCapabilities& HostCapabilities::operator=(const HostCapabilities& other) {
  api_version_ = std::make_unique<HostApiVersion>(*other.api_version_);
  platform_ = other.platform_;
  app_version_ = other.app_version_;
  host_version_ = other.host_version_;
  core_version_ = other.core_version_;
  supports_http3_web_transport_ = other.supports_http3_web_transport_;
  return *this;
}

const HostApiVersion& HostCapabilities::api_version() const {
  return *api_version_;
}

void HostCapabilities::set_api_version(const HostApiVersion& value_arg) {
  api_version_ = std::make_unique<HostApiVersion>(value_arg);
}


const HostPlatform& HostCapabilities::platform() const {
  return platform_;
}

void HostCapabilities::set_platform(const HostPlatform& value_arg) {
  platform_ = value_arg;
}


const std::string& HostCapabilities::app_version() const {
  return app_version_;
}

void HostCapabilities::set_app_version(std::string_view value_arg) {
  app_version_ = value_arg;
}


const std::string& HostCapabilities::host_version() const {
  return host_version_;
}

void HostCapabilities::set_host_version(std::string_view value_arg) {
  host_version_ = value_arg;
}


const std::string& HostCapabilities::core_version() const {
  return core_version_;
}

void HostCapabilities::set_core_version(std::string_view value_arg) {
  core_version_ = value_arg;
}


bool HostCapabilities::supports_http3_web_transport() const {
  return supports_http3_web_transport_;
}

void HostCapabilities::set_supports_http3_web_transport(bool value_arg) {
  supports_http3_web_transport_ = value_arg;
}


EncodableList HostCapabilities::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(CustomEncodableValue(*api_version_));
  list.push_back(CustomEncodableValue(platform_));
  list.push_back(EncodableValue(app_version_));
  list.push_back(EncodableValue(host_version_));
  list.push_back(EncodableValue(core_version_));
  list.push_back(EncodableValue(supports_http3_web_transport_));
  return list;
}

HostCapabilities HostCapabilities::FromEncodableList(const EncodableList& list) {
  HostCapabilities decoded(
    std::any_cast<const HostApiVersion&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const HostPlatform&>(std::get<CustomEncodableValue>(list[1])),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::get<bool>(list[5]));
  return decoded;
}

bool HostCapabilities::operator==(const HostCapabilities& other) const {
  return PigeonInternalDeepEquals(api_version_, other.api_version_) && PigeonInternalDeepEquals(platform_, other.platform_) && PigeonInternalDeepEquals(app_version_, other.app_version_) && PigeonInternalDeepEquals(host_version_, other.host_version_) && PigeonInternalDeepEquals(core_version_, other.core_version_) && PigeonInternalDeepEquals(supports_http3_web_transport_, other.supports_http3_web_transport_);
}

bool HostCapabilities::operator!=(const HostCapabilities& other) const {
  return !(*this == other);
}

size_t HostCapabilities::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(api_version_);
  result = result * 31 + PigeonInternalDeepHash(platform_);
  result = result * 31 + PigeonInternalDeepHash(app_version_);
  result = result * 31 + PigeonInternalDeepHash(host_version_);
  result = result * 31 + PigeonInternalDeepHash(core_version_);
  result = result * 31 + PigeonInternalDeepHash(supports_http3_web_transport_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const HostCapabilities& obj) {
  os << "HostCapabilities(";
  os << "api_version: ";
  os << obj.api_version_;
  os << ", platform: ";
  os << PigeonInternalToString(obj.platform_);
  os << ", app_version: ";
  os << PigeonInternalToString(obj.app_version_);
  os << ", host_version: ";
  os << PigeonInternalToString(obj.host_version_);
  os << ", core_version: ";
  os << PigeonInternalToString(obj.core_version_);
  os << ", supports_http3_web_transport: ";
  os << PigeonInternalToString(obj.supports_http3_web_transport_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const HostCapabilities& v) {
  return v.Hash();
}

// ProfileSummary

ProfileSummary::ProfileSummary(
  const std::string& id,
  const std::string& display_name,
  const std::string& server_identity,
  const std::string& host,
  bool selected,
  bool has_credential,
  const ProfileOrigin& origin,
  bool catalog_managed,
  int64_t updated_at_unix_ms)
 : id_(id),
    display_name_(display_name),
    server_identity_(server_identity),
    host_(host),
    selected_(selected),
    has_credential_(has_credential),
    origin_(origin),
    catalog_managed_(catalog_managed),
    updated_at_unix_ms_(updated_at_unix_ms) {}

const std::string& ProfileSummary::id() const {
  return id_;
}

void ProfileSummary::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string& ProfileSummary::display_name() const {
  return display_name_;
}

void ProfileSummary::set_display_name(std::string_view value_arg) {
  display_name_ = value_arg;
}


const std::string& ProfileSummary::server_identity() const {
  return server_identity_;
}

void ProfileSummary::set_server_identity(std::string_view value_arg) {
  server_identity_ = value_arg;
}


const std::string& ProfileSummary::host() const {
  return host_;
}

void ProfileSummary::set_host(std::string_view value_arg) {
  host_ = value_arg;
}


bool ProfileSummary::selected() const {
  return selected_;
}

void ProfileSummary::set_selected(bool value_arg) {
  selected_ = value_arg;
}


bool ProfileSummary::has_credential() const {
  return has_credential_;
}

void ProfileSummary::set_has_credential(bool value_arg) {
  has_credential_ = value_arg;
}


const ProfileOrigin& ProfileSummary::origin() const {
  return origin_;
}

void ProfileSummary::set_origin(const ProfileOrigin& value_arg) {
  origin_ = value_arg;
}


bool ProfileSummary::catalog_managed() const {
  return catalog_managed_;
}

void ProfileSummary::set_catalog_managed(bool value_arg) {
  catalog_managed_ = value_arg;
}


int64_t ProfileSummary::updated_at_unix_ms() const {
  return updated_at_unix_ms_;
}

void ProfileSummary::set_updated_at_unix_ms(int64_t value_arg) {
  updated_at_unix_ms_ = value_arg;
}


EncodableList ProfileSummary::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(display_name_));
  list.push_back(EncodableValue(server_identity_));
  list.push_back(EncodableValue(host_));
  list.push_back(EncodableValue(selected_));
  list.push_back(EncodableValue(has_credential_));
  list.push_back(CustomEncodableValue(origin_));
  list.push_back(EncodableValue(catalog_managed_));
  list.push_back(EncodableValue(updated_at_unix_ms_));
  return list;
}

ProfileSummary ProfileSummary::FromEncodableList(const EncodableList& list) {
  ProfileSummary decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<bool>(list[4]),
    std::get<bool>(list[5]),
    std::any_cast<const ProfileOrigin&>(std::get<CustomEncodableValue>(list[6])),
    std::get<bool>(list[7]),
    std::get<int64_t>(list[8]));
  return decoded;
}

bool ProfileSummary::operator==(const ProfileSummary& other) const {
  return PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(display_name_, other.display_name_) && PigeonInternalDeepEquals(server_identity_, other.server_identity_) && PigeonInternalDeepEquals(host_, other.host_) && PigeonInternalDeepEquals(selected_, other.selected_) && PigeonInternalDeepEquals(has_credential_, other.has_credential_) && PigeonInternalDeepEquals(origin_, other.origin_) && PigeonInternalDeepEquals(catalog_managed_, other.catalog_managed_) && PigeonInternalDeepEquals(updated_at_unix_ms_, other.updated_at_unix_ms_);
}

bool ProfileSummary::operator!=(const ProfileSummary& other) const {
  return !(*this == other);
}

size_t ProfileSummary::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(display_name_);
  result = result * 31 + PigeonInternalDeepHash(server_identity_);
  result = result * 31 + PigeonInternalDeepHash(host_);
  result = result * 31 + PigeonInternalDeepHash(selected_);
  result = result * 31 + PigeonInternalDeepHash(has_credential_);
  result = result * 31 + PigeonInternalDeepHash(origin_);
  result = result * 31 + PigeonInternalDeepHash(catalog_managed_);
  result = result * 31 + PigeonInternalDeepHash(updated_at_unix_ms_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ProfileSummary& obj) {
  os << "ProfileSummary(";
  os << "id: ";
  os << PigeonInternalToString(obj.id_);
  os << ", display_name: ";
  os << PigeonInternalToString(obj.display_name_);
  os << ", server_identity: ";
  os << PigeonInternalToString(obj.server_identity_);
  os << ", host: ";
  os << PigeonInternalToString(obj.host_);
  os << ", selected: ";
  os << PigeonInternalToString(obj.selected_);
  os << ", has_credential: ";
  os << PigeonInternalToString(obj.has_credential_);
  os << ", origin: ";
  os << PigeonInternalToString(obj.origin_);
  os << ", catalog_managed: ";
  os << PigeonInternalToString(obj.catalog_managed_);
  os << ", updated_at_unix_ms: ";
  os << PigeonInternalToString(obj.updated_at_unix_ms_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ProfileSummary& v) {
  return v.Hash();
}

// ImportProfileRequest

ImportProfileRequest::ImportProfileRequest(
  const std::string& onboarding_value,
  const std::string& operation_id)
 : onboarding_value_(onboarding_value),
    operation_id_(operation_id) {}

const std::string& ImportProfileRequest::onboarding_value() const {
  return onboarding_value_;
}

void ImportProfileRequest::set_onboarding_value(std::string_view value_arg) {
  onboarding_value_ = value_arg;
}


const std::string& ImportProfileRequest::operation_id() const {
  return operation_id_;
}

void ImportProfileRequest::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


EncodableList ImportProfileRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(onboarding_value_));
  list.push_back(EncodableValue(operation_id_));
  return list;
}

ImportProfileRequest ImportProfileRequest::FromEncodableList(const EncodableList& list) {
  ImportProfileRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool ImportProfileRequest::operator==(const ImportProfileRequest& other) const {
  return PigeonInternalDeepEquals(onboarding_value_, other.onboarding_value_) && PigeonInternalDeepEquals(operation_id_, other.operation_id_);
}

bool ImportProfileRequest::operator!=(const ImportProfileRequest& other) const {
  return !(*this == other);
}

size_t ImportProfileRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(onboarding_value_);
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ImportProfileRequest& obj) {
  os << "ImportProfileRequest(";
  os << "onboarding_value: ";
  os << PigeonInternalToString(obj.onboarding_value_);
  os << ", operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ImportProfileRequest& v) {
  return v.Hash();
}

// SelectProfileRequest

SelectProfileRequest::SelectProfileRequest(
  const std::string& profile_id,
  const std::string& operation_id)
 : profile_id_(profile_id),
    operation_id_(operation_id) {}

const std::string& SelectProfileRequest::profile_id() const {
  return profile_id_;
}

void SelectProfileRequest::set_profile_id(std::string_view value_arg) {
  profile_id_ = value_arg;
}


const std::string& SelectProfileRequest::operation_id() const {
  return operation_id_;
}

void SelectProfileRequest::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


EncodableList SelectProfileRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(profile_id_));
  list.push_back(EncodableValue(operation_id_));
  return list;
}

SelectProfileRequest SelectProfileRequest::FromEncodableList(const EncodableList& list) {
  SelectProfileRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool SelectProfileRequest::operator==(const SelectProfileRequest& other) const {
  return PigeonInternalDeepEquals(profile_id_, other.profile_id_) && PigeonInternalDeepEquals(operation_id_, other.operation_id_);
}

bool SelectProfileRequest::operator!=(const SelectProfileRequest& other) const {
  return !(*this == other);
}

size_t SelectProfileRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(profile_id_);
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const SelectProfileRequest& obj) {
  os << "SelectProfileRequest(";
  os << "profile_id: ";
  os << PigeonInternalToString(obj.profile_id_);
  os << ", operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const SelectProfileRequest& v) {
  return v.Hash();
}

// RemoveProfileRequest

RemoveProfileRequest::RemoveProfileRequest(
  const std::string& profile_id,
  bool force,
  const std::string& operation_id)
 : profile_id_(profile_id),
    force_(force),
    operation_id_(operation_id) {}

const std::string& RemoveProfileRequest::profile_id() const {
  return profile_id_;
}

void RemoveProfileRequest::set_profile_id(std::string_view value_arg) {
  profile_id_ = value_arg;
}


bool RemoveProfileRequest::force() const {
  return force_;
}

void RemoveProfileRequest::set_force(bool value_arg) {
  force_ = value_arg;
}


const std::string& RemoveProfileRequest::operation_id() const {
  return operation_id_;
}

void RemoveProfileRequest::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


EncodableList RemoveProfileRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(profile_id_));
  list.push_back(EncodableValue(force_));
  list.push_back(EncodableValue(operation_id_));
  return list;
}

RemoveProfileRequest RemoveProfileRequest::FromEncodableList(const EncodableList& list) {
  RemoveProfileRequest decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[1]),
    std::get<std::string>(list[2]));
  return decoded;
}

bool RemoveProfileRequest::operator==(const RemoveProfileRequest& other) const {
  return PigeonInternalDeepEquals(profile_id_, other.profile_id_) && PigeonInternalDeepEquals(force_, other.force_) && PigeonInternalDeepEquals(operation_id_, other.operation_id_);
}

bool RemoveProfileRequest::operator!=(const RemoveProfileRequest& other) const {
  return !(*this == other);
}

size_t RemoveProfileRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(profile_id_);
  result = result * 31 + PigeonInternalDeepHash(force_);
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const RemoveProfileRequest& obj) {
  os << "RemoveProfileRequest(";
  os << "profile_id: ";
  os << PigeonInternalToString(obj.profile_id_);
  os << ", force: ";
  os << PigeonInternalToString(obj.force_);
  os << ", operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const RemoveProfileRequest& v) {
  return v.Hash();
}

// ConnectRequest

ConnectRequest::ConnectRequest(
  const std::string& profile_id,
  const std::string& operation_id)
 : profile_id_(profile_id),
    operation_id_(operation_id) {}

const std::string& ConnectRequest::profile_id() const {
  return profile_id_;
}

void ConnectRequest::set_profile_id(std::string_view value_arg) {
  profile_id_ = value_arg;
}


const std::string& ConnectRequest::operation_id() const {
  return operation_id_;
}

void ConnectRequest::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


EncodableList ConnectRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(profile_id_));
  list.push_back(EncodableValue(operation_id_));
  return list;
}

ConnectRequest ConnectRequest::FromEncodableList(const EncodableList& list) {
  ConnectRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool ConnectRequest::operator==(const ConnectRequest& other) const {
  return PigeonInternalDeepEquals(profile_id_, other.profile_id_) && PigeonInternalDeepEquals(operation_id_, other.operation_id_);
}

bool ConnectRequest::operator!=(const ConnectRequest& other) const {
  return !(*this == other);
}

size_t ConnectRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(profile_id_);
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ConnectRequest& obj) {
  os << "ConnectRequest(";
  os << "profile_id: ";
  os << PigeonInternalToString(obj.profile_id_);
  os << ", operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ConnectRequest& v) {
  return v.Hash();
}

// DisconnectRequest

DisconnectRequest::DisconnectRequest(const std::string& operation_id)
 : operation_id_(operation_id) {}

const std::string& DisconnectRequest::operation_id() const {
  return operation_id_;
}

void DisconnectRequest::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


EncodableList DisconnectRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(EncodableValue(operation_id_));
  return list;
}

DisconnectRequest DisconnectRequest::FromEncodableList(const EncodableList& list) {
  DisconnectRequest decoded(
    std::get<std::string>(list[0]));
  return decoded;
}

bool DisconnectRequest::operator==(const DisconnectRequest& other) const {
  return PigeonInternalDeepEquals(operation_id_, other.operation_id_);
}

bool DisconnectRequest::operator!=(const DisconnectRequest& other) const {
  return !(*this == other);
}

size_t DisconnectRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DisconnectRequest& obj) {
  os << "DisconnectRequest(";
  os << "operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DisconnectRequest& v) {
  return v.Hash();
}

// HostError

HostError::HostError(
  const HostErrorCode& code,
  const ErrorStage& stage,
  const std::string& message,
  bool retryable,
  const std::string& operation_id)
 : code_(code),
    stage_(stage),
    message_(message),
    retryable_(retryable),
    operation_id_(operation_id) {}

const HostErrorCode& HostError::code() const {
  return code_;
}

void HostError::set_code(const HostErrorCode& value_arg) {
  code_ = value_arg;
}


const ErrorStage& HostError::stage() const {
  return stage_;
}

void HostError::set_stage(const ErrorStage& value_arg) {
  stage_ = value_arg;
}


const std::string& HostError::message() const {
  return message_;
}

void HostError::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


bool HostError::retryable() const {
  return retryable_;
}

void HostError::set_retryable(bool value_arg) {
  retryable_ = value_arg;
}


const std::string& HostError::operation_id() const {
  return operation_id_;
}

void HostError::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


EncodableList HostError::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(CustomEncodableValue(code_));
  list.push_back(CustomEncodableValue(stage_));
  list.push_back(EncodableValue(message_));
  list.push_back(EncodableValue(retryable_));
  list.push_back(EncodableValue(operation_id_));
  return list;
}

HostError HostError::FromEncodableList(const EncodableList& list) {
  HostError decoded(
    std::any_cast<const HostErrorCode&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const ErrorStage&>(std::get<CustomEncodableValue>(list[1])),
    std::get<std::string>(list[2]),
    std::get<bool>(list[3]),
    std::get<std::string>(list[4]));
  return decoded;
}

bool HostError::operator==(const HostError& other) const {
  return PigeonInternalDeepEquals(code_, other.code_) && PigeonInternalDeepEquals(stage_, other.stage_) && PigeonInternalDeepEquals(message_, other.message_) && PigeonInternalDeepEquals(retryable_, other.retryable_) && PigeonInternalDeepEquals(operation_id_, other.operation_id_);
}

bool HostError::operator!=(const HostError& other) const {
  return !(*this == other);
}

size_t HostError::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(code_);
  result = result * 31 + PigeonInternalDeepHash(stage_);
  result = result * 31 + PigeonInternalDeepHash(message_);
  result = result * 31 + PigeonInternalDeepHash(retryable_);
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const HostError& obj) {
  os << "HostError(";
  os << "code: ";
  os << PigeonInternalToString(obj.code_);
  os << ", stage: ";
  os << PigeonInternalToString(obj.stage_);
  os << ", message: ";
  os << PigeonInternalToString(obj.message_);
  os << ", retryable: ";
  os << PigeonInternalToString(obj.retryable_);
  os << ", operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const HostError& v) {
  return v.Hash();
}

// TunnelStatus

TunnelStatus::TunnelStatus(
  const TunnelState& state,
  const CarrierKind& carrier,
  int64_t connected_at_unix_ms,
  int64_t upload_bytes_per_second,
  int64_t download_bytes_per_second,
  int64_t upload_total_bytes,
  int64_t download_total_bytes,
  int64_t sequence)
 : state_(state),
    carrier_(carrier),
    connected_at_unix_ms_(connected_at_unix_ms),
    upload_bytes_per_second_(upload_bytes_per_second),
    download_bytes_per_second_(download_bytes_per_second),
    upload_total_bytes_(upload_total_bytes),
    download_total_bytes_(download_total_bytes),
    sequence_(sequence) {}

TunnelStatus::TunnelStatus(
  const TunnelState& state,
  const std::string* profile_id,
  const CarrierKind& carrier,
  int64_t connected_at_unix_ms,
  int64_t upload_bytes_per_second,
  int64_t download_bytes_per_second,
  int64_t upload_total_bytes,
  int64_t download_total_bytes,
  int64_t sequence,
  const HostError* last_error)
 : state_(state),
    profile_id_(profile_id ? std::optional<std::string>(*profile_id) : std::nullopt),
    carrier_(carrier),
    connected_at_unix_ms_(connected_at_unix_ms),
    upload_bytes_per_second_(upload_bytes_per_second),
    download_bytes_per_second_(download_bytes_per_second),
    upload_total_bytes_(upload_total_bytes),
    download_total_bytes_(download_total_bytes),
    sequence_(sequence),
    last_error_(last_error ? std::make_unique<HostError>(*last_error) : nullptr) {}

TunnelStatus::TunnelStatus(const TunnelStatus& other)
 : state_(other.state_),
    profile_id_(other.profile_id_ ? std::optional<std::string>(*other.profile_id_) : std::nullopt),
    carrier_(other.carrier_),
    connected_at_unix_ms_(other.connected_at_unix_ms_),
    upload_bytes_per_second_(other.upload_bytes_per_second_),
    download_bytes_per_second_(other.download_bytes_per_second_),
    upload_total_bytes_(other.upload_total_bytes_),
    download_total_bytes_(other.download_total_bytes_),
    sequence_(other.sequence_),
    last_error_(other.last_error_ ? std::make_unique<HostError>(*other.last_error_) : nullptr) {}

TunnelStatus& TunnelStatus::operator=(const TunnelStatus& other) {
  state_ = other.state_;
  profile_id_ = other.profile_id_;
  carrier_ = other.carrier_;
  connected_at_unix_ms_ = other.connected_at_unix_ms_;
  upload_bytes_per_second_ = other.upload_bytes_per_second_;
  download_bytes_per_second_ = other.download_bytes_per_second_;
  upload_total_bytes_ = other.upload_total_bytes_;
  download_total_bytes_ = other.download_total_bytes_;
  sequence_ = other.sequence_;
  last_error_ = other.last_error_ ? std::make_unique<HostError>(*other.last_error_) : nullptr;
  return *this;
}

const TunnelState& TunnelStatus::state() const {
  return state_;
}

void TunnelStatus::set_state(const TunnelState& value_arg) {
  state_ = value_arg;
}


const std::string* TunnelStatus::profile_id() const {
  return profile_id_ ? &(*profile_id_) : nullptr;
}

void TunnelStatus::set_profile_id(const std::string_view* value_arg) {
  profile_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void TunnelStatus::set_profile_id(std::string_view value_arg) {
  profile_id_ = value_arg;
}


const CarrierKind& TunnelStatus::carrier() const {
  return carrier_;
}

void TunnelStatus::set_carrier(const CarrierKind& value_arg) {
  carrier_ = value_arg;
}


int64_t TunnelStatus::connected_at_unix_ms() const {
  return connected_at_unix_ms_;
}

void TunnelStatus::set_connected_at_unix_ms(int64_t value_arg) {
  connected_at_unix_ms_ = value_arg;
}


int64_t TunnelStatus::upload_bytes_per_second() const {
  return upload_bytes_per_second_;
}

void TunnelStatus::set_upload_bytes_per_second(int64_t value_arg) {
  upload_bytes_per_second_ = value_arg;
}


int64_t TunnelStatus::download_bytes_per_second() const {
  return download_bytes_per_second_;
}

void TunnelStatus::set_download_bytes_per_second(int64_t value_arg) {
  download_bytes_per_second_ = value_arg;
}


int64_t TunnelStatus::upload_total_bytes() const {
  return upload_total_bytes_;
}

void TunnelStatus::set_upload_total_bytes(int64_t value_arg) {
  upload_total_bytes_ = value_arg;
}


int64_t TunnelStatus::download_total_bytes() const {
  return download_total_bytes_;
}

void TunnelStatus::set_download_total_bytes(int64_t value_arg) {
  download_total_bytes_ = value_arg;
}


int64_t TunnelStatus::sequence() const {
  return sequence_;
}

void TunnelStatus::set_sequence(int64_t value_arg) {
  sequence_ = value_arg;
}


const HostError* TunnelStatus::last_error() const {
  return last_error_.get();
}

void TunnelStatus::set_last_error(const HostError* value_arg) {
  last_error_ = value_arg ? std::make_unique<HostError>(*value_arg) : nullptr;
}

void TunnelStatus::set_last_error(const HostError& value_arg) {
  last_error_ = std::make_unique<HostError>(value_arg);
}


EncodableList TunnelStatus::ToEncodableList() const {
  EncodableList list;
  list.reserve(10);
  list.push_back(CustomEncodableValue(state_));
  list.push_back(profile_id_ ? EncodableValue(*profile_id_) : EncodableValue());
  list.push_back(CustomEncodableValue(carrier_));
  list.push_back(EncodableValue(connected_at_unix_ms_));
  list.push_back(EncodableValue(upload_bytes_per_second_));
  list.push_back(EncodableValue(download_bytes_per_second_));
  list.push_back(EncodableValue(upload_total_bytes_));
  list.push_back(EncodableValue(download_total_bytes_));
  list.push_back(EncodableValue(sequence_));
  list.push_back(last_error_ ? CustomEncodableValue(*last_error_) : EncodableValue());
  return list;
}

TunnelStatus TunnelStatus::FromEncodableList(const EncodableList& list) {
  TunnelStatus decoded(
    std::any_cast<const TunnelState&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const CarrierKind&>(std::get<CustomEncodableValue>(list[2])),
    std::get<int64_t>(list[3]),
    std::get<int64_t>(list[4]),
    std::get<int64_t>(list[5]),
    std::get<int64_t>(list[6]),
    std::get<int64_t>(list[7]),
    std::get<int64_t>(list[8]));
  auto& encodable_profile_id = list[1];
  if (!encodable_profile_id.IsNull()) {
    decoded.set_profile_id(std::get<std::string>(encodable_profile_id));
  }
  auto& encodable_last_error = list[9];
  if (!encodable_last_error.IsNull()) {
    decoded.set_last_error(std::any_cast<const HostError&>(std::get<CustomEncodableValue>(encodable_last_error)));
  }
  return decoded;
}

bool TunnelStatus::operator==(const TunnelStatus& other) const {
  return PigeonInternalDeepEquals(state_, other.state_) && PigeonInternalDeepEquals(profile_id_, other.profile_id_) && PigeonInternalDeepEquals(carrier_, other.carrier_) && PigeonInternalDeepEquals(connected_at_unix_ms_, other.connected_at_unix_ms_) && PigeonInternalDeepEquals(upload_bytes_per_second_, other.upload_bytes_per_second_) && PigeonInternalDeepEquals(download_bytes_per_second_, other.download_bytes_per_second_) && PigeonInternalDeepEquals(upload_total_bytes_, other.upload_total_bytes_) && PigeonInternalDeepEquals(download_total_bytes_, other.download_total_bytes_) && PigeonInternalDeepEquals(sequence_, other.sequence_) && PigeonInternalDeepEquals(last_error_, other.last_error_);
}

bool TunnelStatus::operator!=(const TunnelStatus& other) const {
  return !(*this == other);
}

size_t TunnelStatus::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(state_);
  result = result * 31 + PigeonInternalDeepHash(profile_id_);
  result = result * 31 + PigeonInternalDeepHash(carrier_);
  result = result * 31 + PigeonInternalDeepHash(connected_at_unix_ms_);
  result = result * 31 + PigeonInternalDeepHash(upload_bytes_per_second_);
  result = result * 31 + PigeonInternalDeepHash(download_bytes_per_second_);
  result = result * 31 + PigeonInternalDeepHash(upload_total_bytes_);
  result = result * 31 + PigeonInternalDeepHash(download_total_bytes_);
  result = result * 31 + PigeonInternalDeepHash(sequence_);
  result = result * 31 + PigeonInternalDeepHash(last_error_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const TunnelStatus& obj) {
  os << "TunnelStatus(";
  os << "state: ";
  os << PigeonInternalToString(obj.state_);
  os << ", profile_id: ";
  if (obj.profile_id_) {
    os << PigeonInternalToString(*obj.profile_id_);
  }
  else {
    os << "null";
  }
  os << ", carrier: ";
  os << PigeonInternalToString(obj.carrier_);
  os << ", connected_at_unix_ms: ";
  os << PigeonInternalToString(obj.connected_at_unix_ms_);
  os << ", upload_bytes_per_second: ";
  os << PigeonInternalToString(obj.upload_bytes_per_second_);
  os << ", download_bytes_per_second: ";
  os << PigeonInternalToString(obj.download_bytes_per_second_);
  os << ", upload_total_bytes: ";
  os << PigeonInternalToString(obj.upload_total_bytes_);
  os << ", download_total_bytes: ";
  os << PigeonInternalToString(obj.download_total_bytes_);
  os << ", sequence: ";
  os << PigeonInternalToString(obj.sequence_);
  os << ", last_error: ";
  if (obj.last_error_) {
    os << *obj.last_error_;
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const TunnelStatus& v) {
  return v.Hash();
}

// DiagnosticsRequest

DiagnosticsRequest::DiagnosticsRequest(int64_t limit)
 : limit_(limit) {}

int64_t DiagnosticsRequest::limit() const {
  return limit_;
}

void DiagnosticsRequest::set_limit(int64_t value_arg) {
  limit_ = value_arg;
}


EncodableList DiagnosticsRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(EncodableValue(limit_));
  return list;
}

DiagnosticsRequest DiagnosticsRequest::FromEncodableList(const EncodableList& list) {
  DiagnosticsRequest decoded(
    std::get<int64_t>(list[0]));
  return decoded;
}

bool DiagnosticsRequest::operator==(const DiagnosticsRequest& other) const {
  return PigeonInternalDeepEquals(limit_, other.limit_);
}

bool DiagnosticsRequest::operator!=(const DiagnosticsRequest& other) const {
  return !(*this == other);
}

size_t DiagnosticsRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(limit_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DiagnosticsRequest& obj) {
  os << "DiagnosticsRequest(";
  os << "limit: ";
  os << PigeonInternalToString(obj.limit_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DiagnosticsRequest& v) {
  return v.Hash();
}

// DiagnosticEvent

DiagnosticEvent::DiagnosticEvent(
  int64_t unix_ms,
  const DiagnosticLevel& level,
  const ErrorStage& stage,
  const std::string& message,
  const std::string& operation_id,
  int64_t sequence)
 : unix_ms_(unix_ms),
    level_(level),
    stage_(stage),
    message_(message),
    operation_id_(operation_id),
    sequence_(sequence) {}

DiagnosticEvent::DiagnosticEvent(
  int64_t unix_ms,
  const DiagnosticLevel& level,
  const ErrorStage& stage,
  const HostErrorCode* code,
  const std::string& message,
  const std::string& operation_id,
  int64_t sequence)
 : unix_ms_(unix_ms),
    level_(level),
    stage_(stage),
    code_(code ? std::optional<HostErrorCode>(*code) : std::nullopt),
    message_(message),
    operation_id_(operation_id),
    sequence_(sequence) {}

int64_t DiagnosticEvent::unix_ms() const {
  return unix_ms_;
}

void DiagnosticEvent::set_unix_ms(int64_t value_arg) {
  unix_ms_ = value_arg;
}


const DiagnosticLevel& DiagnosticEvent::level() const {
  return level_;
}

void DiagnosticEvent::set_level(const DiagnosticLevel& value_arg) {
  level_ = value_arg;
}


const ErrorStage& DiagnosticEvent::stage() const {
  return stage_;
}

void DiagnosticEvent::set_stage(const ErrorStage& value_arg) {
  stage_ = value_arg;
}


const HostErrorCode* DiagnosticEvent::code() const {
  return code_ ? &(*code_) : nullptr;
}

void DiagnosticEvent::set_code(const HostErrorCode* value_arg) {
  code_ = value_arg ? std::optional<HostErrorCode>(*value_arg) : std::nullopt;
}

void DiagnosticEvent::set_code(const HostErrorCode& value_arg) {
  code_ = value_arg;
}


const std::string& DiagnosticEvent::message() const {
  return message_;
}

void DiagnosticEvent::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


const std::string& DiagnosticEvent::operation_id() const {
  return operation_id_;
}

void DiagnosticEvent::set_operation_id(std::string_view value_arg) {
  operation_id_ = value_arg;
}


int64_t DiagnosticEvent::sequence() const {
  return sequence_;
}

void DiagnosticEvent::set_sequence(int64_t value_arg) {
  sequence_ = value_arg;
}


EncodableList DiagnosticEvent::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(unix_ms_));
  list.push_back(CustomEncodableValue(level_));
  list.push_back(CustomEncodableValue(stage_));
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(EncodableValue(message_));
  list.push_back(EncodableValue(operation_id_));
  list.push_back(EncodableValue(sequence_));
  return list;
}

DiagnosticEvent DiagnosticEvent::FromEncodableList(const EncodableList& list) {
  DiagnosticEvent decoded(
    std::get<int64_t>(list[0]),
    std::any_cast<const DiagnosticLevel&>(std::get<CustomEncodableValue>(list[1])),
    std::any_cast<const ErrorStage&>(std::get<CustomEncodableValue>(list[2])),
    std::get<std::string>(list[4]),
    std::get<std::string>(list[5]),
    std::get<int64_t>(list[6]));
  auto& encodable_code = list[3];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const HostErrorCode&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  return decoded;
}

bool DiagnosticEvent::operator==(const DiagnosticEvent& other) const {
  return PigeonInternalDeepEquals(unix_ms_, other.unix_ms_) && PigeonInternalDeepEquals(level_, other.level_) && PigeonInternalDeepEquals(stage_, other.stage_) && PigeonInternalDeepEquals(code_, other.code_) && PigeonInternalDeepEquals(message_, other.message_) && PigeonInternalDeepEquals(operation_id_, other.operation_id_) && PigeonInternalDeepEquals(sequence_, other.sequence_);
}

bool DiagnosticEvent::operator!=(const DiagnosticEvent& other) const {
  return !(*this == other);
}

size_t DiagnosticEvent::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(unix_ms_);
  result = result * 31 + PigeonInternalDeepHash(level_);
  result = result * 31 + PigeonInternalDeepHash(stage_);
  result = result * 31 + PigeonInternalDeepHash(code_);
  result = result * 31 + PigeonInternalDeepHash(message_);
  result = result * 31 + PigeonInternalDeepHash(operation_id_);
  result = result * 31 + PigeonInternalDeepHash(sequence_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DiagnosticEvent& obj) {
  os << "DiagnosticEvent(";
  os << "unix_ms: ";
  os << PigeonInternalToString(obj.unix_ms_);
  os << ", level: ";
  os << PigeonInternalToString(obj.level_);
  os << ", stage: ";
  os << PigeonInternalToString(obj.stage_);
  os << ", code: ";
  if (obj.code_) {
    os << PigeonInternalToString(*obj.code_);
  }
  else {
    os << "null";
  }
  os << ", message: ";
  os << PigeonInternalToString(obj.message_);
  os << ", operation_id: ";
  os << PigeonInternalToString(obj.operation_id_);
  os << ", sequence: ";
  os << PigeonInternalToString(obj.sequence_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DiagnosticEvent& v) {
  return v.Hash();
}

// DiagnosticsSnapshot

DiagnosticsSnapshot::DiagnosticsSnapshot(
  const std::string& app_version,
  const std::string& host_version,
  const std::string& core_version,
  const std::string& carrier_policy,
  const CarrierKind& current_carrier,
  int64_t reconnect_count,
  const EncodableList& events)
 : app_version_(app_version),
    host_version_(host_version),
    core_version_(core_version),
    carrier_policy_(carrier_policy),
    current_carrier_(current_carrier),
    reconnect_count_(reconnect_count),
    events_(events) {}

const std::string& DiagnosticsSnapshot::app_version() const {
  return app_version_;
}

void DiagnosticsSnapshot::set_app_version(std::string_view value_arg) {
  app_version_ = value_arg;
}


const std::string& DiagnosticsSnapshot::host_version() const {
  return host_version_;
}

void DiagnosticsSnapshot::set_host_version(std::string_view value_arg) {
  host_version_ = value_arg;
}


const std::string& DiagnosticsSnapshot::core_version() const {
  return core_version_;
}

void DiagnosticsSnapshot::set_core_version(std::string_view value_arg) {
  core_version_ = value_arg;
}


const std::string& DiagnosticsSnapshot::carrier_policy() const {
  return carrier_policy_;
}

void DiagnosticsSnapshot::set_carrier_policy(std::string_view value_arg) {
  carrier_policy_ = value_arg;
}


const CarrierKind& DiagnosticsSnapshot::current_carrier() const {
  return current_carrier_;
}

void DiagnosticsSnapshot::set_current_carrier(const CarrierKind& value_arg) {
  current_carrier_ = value_arg;
}


int64_t DiagnosticsSnapshot::reconnect_count() const {
  return reconnect_count_;
}

void DiagnosticsSnapshot::set_reconnect_count(int64_t value_arg) {
  reconnect_count_ = value_arg;
}


const EncodableList& DiagnosticsSnapshot::events() const {
  return events_;
}

void DiagnosticsSnapshot::set_events(const EncodableList& value_arg) {
  events_ = value_arg;
}


EncodableList DiagnosticsSnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(app_version_));
  list.push_back(EncodableValue(host_version_));
  list.push_back(EncodableValue(core_version_));
  list.push_back(EncodableValue(carrier_policy_));
  list.push_back(CustomEncodableValue(current_carrier_));
  list.push_back(EncodableValue(reconnect_count_));
  list.push_back(EncodableValue(events_));
  return list;
}

DiagnosticsSnapshot DiagnosticsSnapshot::FromEncodableList(const EncodableList& list) {
  DiagnosticsSnapshot decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::any_cast<const CarrierKind&>(std::get<CustomEncodableValue>(list[4])),
    std::get<int64_t>(list[5]),
    std::get<EncodableList>(list[6]));
  return decoded;
}

bool DiagnosticsSnapshot::operator==(const DiagnosticsSnapshot& other) const {
  return PigeonInternalDeepEquals(app_version_, other.app_version_) && PigeonInternalDeepEquals(host_version_, other.host_version_) && PigeonInternalDeepEquals(core_version_, other.core_version_) && PigeonInternalDeepEquals(carrier_policy_, other.carrier_policy_) && PigeonInternalDeepEquals(current_carrier_, other.current_carrier_) && PigeonInternalDeepEquals(reconnect_count_, other.reconnect_count_) && PigeonInternalDeepEquals(events_, other.events_);
}

bool DiagnosticsSnapshot::operator!=(const DiagnosticsSnapshot& other) const {
  return !(*this == other);
}

size_t DiagnosticsSnapshot::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(app_version_);
  result = result * 31 + PigeonInternalDeepHash(host_version_);
  result = result * 31 + PigeonInternalDeepHash(core_version_);
  result = result * 31 + PigeonInternalDeepHash(carrier_policy_);
  result = result * 31 + PigeonInternalDeepHash(current_carrier_);
  result = result * 31 + PigeonInternalDeepHash(reconnect_count_);
  result = result * 31 + PigeonInternalDeepHash(events_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DiagnosticsSnapshot& obj) {
  os << "DiagnosticsSnapshot(";
  os << "app_version: ";
  os << PigeonInternalToString(obj.app_version_);
  os << ", host_version: ";
  os << PigeonInternalToString(obj.host_version_);
  os << ", core_version: ";
  os << PigeonInternalToString(obj.core_version_);
  os << ", carrier_policy: ";
  os << PigeonInternalToString(obj.carrier_policy_);
  os << ", current_carrier: ";
  os << PigeonInternalToString(obj.current_carrier_);
  os << ", reconnect_count: ";
  os << PigeonInternalToString(obj.reconnect_count_);
  os << ", events: ";
  os << PigeonInternalToString(obj.events_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DiagnosticsSnapshot& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<HostPlatform>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ProfileOrigin>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<TunnelState>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<CarrierKind>(enum_arg_value));
      }
    case 133: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<HostErrorCode>(enum_arg_value));
      }
    case 134: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ErrorStage>(enum_arg_value));
      }
    case 135: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<DiagnosticLevel>(enum_arg_value));
      }
    case 136: {
        return CustomEncodableValue(HostApiVersion::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(HostCapabilities::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(ProfileSummary::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 139: {
        return CustomEncodableValue(ImportProfileRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 140: {
        return CustomEncodableValue(SelectProfileRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 141: {
        return CustomEncodableValue(RemoveProfileRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 142: {
        return CustomEncodableValue(ConnectRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 143: {
        return CustomEncodableValue(DisconnectRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 144: {
        return CustomEncodableValue(HostError::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 145: {
        return CustomEncodableValue(TunnelStatus::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 146: {
        return CustomEncodableValue(DiagnosticsRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 147: {
        return CustomEncodableValue(DiagnosticEvent::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 148: {
        return CustomEncodableValue(DiagnosticsSnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(HostPlatform)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<HostPlatform>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ProfileOrigin)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ProfileOrigin>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(TunnelState)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<TunnelState>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(CarrierKind)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<CarrierKind>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(HostErrorCode)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<HostErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ErrorStage)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ErrorStage>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(DiagnosticLevel)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<DiagnosticLevel>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(HostApiVersion)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<HostApiVersion>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(HostCapabilities)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<HostCapabilities>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ProfileSummary)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<ProfileSummary>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ImportProfileRequest)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<ImportProfileRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(SelectProfileRequest)) {
      stream->WriteByte(140);
      WriteValue(EncodableValue(std::any_cast<SelectProfileRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RemoveProfileRequest)) {
      stream->WriteByte(141);
      WriteValue(EncodableValue(std::any_cast<RemoveProfileRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ConnectRequest)) {
      stream->WriteByte(142);
      WriteValue(EncodableValue(std::any_cast<ConnectRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DisconnectRequest)) {
      stream->WriteByte(143);
      WriteValue(EncodableValue(std::any_cast<DisconnectRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(HostError)) {
      stream->WriteByte(144);
      WriteValue(EncodableValue(std::any_cast<HostError>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(TunnelStatus)) {
      stream->WriteByte(145);
      WriteValue(EncodableValue(std::any_cast<TunnelStatus>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiagnosticsRequest)) {
      stream->WriteByte(146);
      WriteValue(EncodableValue(std::any_cast<DiagnosticsRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiagnosticEvent)) {
      stream->WriteByte(147);
      WriteValue(EncodableValue(std::any_cast<DiagnosticEvent>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiagnosticsSnapshot)) {
      stream->WriteByte(148);
      WriteValue(EncodableValue(std::any_cast<DiagnosticsSnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by ClientHostApi.
const ::flutter::StandardMessageCodec& ClientHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `ClientHostApi` to handle messages through the `binary_messenger`.
void ClientHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  ClientHostApi* api) {
  ClientHostApi::SetUp(binary_messenger, api, "");
}

void ClientHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  ClientHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.getCapabilities" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_requested_version_arg = args.at(0);
          if (encodable_requested_version_arg.IsNull()) {
            reply(WrapError("requested_version_arg unexpectedly null."));
            return;
          }
          const auto& requested_version_arg = std::any_cast<const HostApiVersion&>(std::get<CustomEncodableValue>(encodable_requested_version_arg));
          api->GetCapabilities(requested_version_arg, [reply](ErrorOr<HostCapabilities>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.listProfiles" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ListProfiles([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.importProfile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const ImportProfileRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->ImportProfile(request_arg, [reply](ErrorOr<ProfileSummary>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.selectProfile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const SelectProfileRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->SelectProfile(request_arg, [reply](ErrorOr<ProfileSummary>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.removeProfile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const RemoveProfileRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->RemoveProfile(request_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.connect" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const ConnectRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->Connect(request_arg, [reply](ErrorOr<TunnelStatus>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.disconnect" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const DisconnectRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->Disconnect(request_arg, [reply](ErrorOr<TunnelStatus>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.getStatus" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetStatus([reply](ErrorOr<TunnelStatus>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.neproto_host.ClientHostApi.getDiagnostics" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const DiagnosticsRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->GetDiagnostics(request_arg, [reply](ErrorOr<DiagnosticsSnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue ClientHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue ClientHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
ClientHostFlutterApi::ClientHostFlutterApi(::flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

ClientHostFlutterApi::ClientHostFlutterApi(
  ::flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const ::flutter::StandardMessageCodec& ClientHostFlutterApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void ClientHostFlutterApi::StatusChanged(
  const TunnelStatus& status_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.neproto_host.ClientHostFlutterApi.statusChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(status_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    }
  });
}

}  // namespace neproto_host
